### PR TITLE
Enables running commands via console

### PR DESCRIPTION
**Pull request by EarthCow**
Allows the console to issue commands in addition to players.

### CODE REVIEW

**Comment by natereprogle** [comment]
> Allows the console to issue commands in addition to players.

I assume if Console is the CommandSender it will have permission, is that correct? As stupid as it sounds, I’m unfamiliar with this, normally I’ve just checked if the sender was console 😅

**Comment by EarthCow** [comment]
Of course it's not stupid. By default, the `ConsoleCommandSender` implementation is an operator and therefore has all permissions. Checking if the `CommandSender` is console is a perfectly fine approach, but I don't believe it's necessary unless you want to change the behavior of the command based on what runs it.

**Comment by natereprogle** [comment]
In that case, LGTM! I had some other work that I wanted to put in the next update, but I think I’m going to release an update that at least gets your work out there! Thanks for the multiple PR’s you’ve submitted

**Comment by EarthCow** [comment]
Sure! I've just been adding some functionality that my server needed and figured I'd post the PRs just in case anyone else found it useful. No need to rush the update if you're working on something else. Thanks 👍

**Pull request merged**
